//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int SoHoaDon { get; set; }
        public Nullable<int> SoPhieuKhamBenh { get; set; }
        public int TienKham { get; set; }
        public int TienThuoc { get; set; }
    
        public virtual PHIEUKHAMBENH PHIEUKHAMBENH { get; set; }
    }
}
