//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.BENH = new HashSet<BENH>();
            this.CT_PHIEUKHAMBENH = new HashSet<CT_PHIEUKHAMBENH>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
            this.CHITIETBCSUDUNGTHUOC = new HashSet<CHITIETBCSUDUNGTHUOC>();
        }
    
        public int id { get; set; }
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public int idMaDonVi { get; set; }
        public int idMaCachDung { get; set; }
        public int SoLuongTon { get; set; }
        public int DonGia { get; set; }
        public string CongDung { get; set; }
        public string HuongDanSuDung { get; set; }
        public int idMaLoaiThuoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENH> BENH { get; set; }
        public virtual CACHDUNG CACHDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBCSUDUNGTHUOC> CHITIETBCSUDUNGTHUOC { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual LOAITHUOC LOAITHUOC { get; set; }
    }
}
